### ISSUE TITLE
ReferenceError: WSClientHandler is not defined

### ISSUE THREAD

**Issue by paulferrett** [smilefam/SendBird-JavaScript#59]
Hi There, receiving the following error when internet connection is lost

```
/node_modules/sendbird/SendBird.min.js:7
p.mention_type=c,p.mentioned_user_ids=[],c===de.MentionType.CHANNEL?p.mentioned_user_ids=[]:Array.isArray(d)&&d.length>0&&(p.mentioned_user_ids=d),h&&h!==pe.PushNotificationDeliveryOption.DEFAULT&&(p.push_option=h),new W("FILE",p,e)},W.bPing=function(){var e={};return e.id=(new Date).getTime(),new W("PING",e)},W.bEnter=function(e){var n={};return n.channel_url=e,new W("ENTR",n)},W.bExit=function(e){var n={};return n.channel_url=e,new W("EXIT",n)},W.bUpdateUserMessage=function(e,n,t,r,i,a,s){var o={};return o.channel_url=e,o.msg_id=n,null!=t&&t!==undefined&&(o.message=t),null!=r&&r!==undefined&&(o.data=r),null!=i&&i!==undefined&&(o.custom_type=i),new W("MEDI",o)},W.bUpdateFileMessage=function(e,n,t,r,i,a){var s={};return s.channel_url=e,s.msg_id=n,null!=t&&t!==undefined&&(s.data=t),null!=r&&r!==undefined&&(s.custom_type=r),new W("FEDI",s)},W.requestIdSeed=(new Date).getTime(),W.generateRequestId=function(){return W.requestIdSeed++,String(W.r

ReferenceError: WSClientHandler is not defined
    at Timeout.<anonymous> (/node_modules/sendbird/SendBird.min.js:7:17818)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by Alchemist85K** [comment]
Hi @paulferrett  ~.
Thank you for your interest in SendBird SDK. :)
Could you tell me what version you're using?
This problem has been solved in the latest version. 
Please use the latest version.

**Comment by paulferrett** [comment]
Thanks for the quick reply. I was on `3.0.71` and have upgraded to `3.0.75`.

This fixed the above issue, however now it doesn't work at all for me with the following error.

I'm running in node `v8.11.4`

```
/node_modules/sendbird/SendBird.min.js:5
!function(e,n){"object"==typeof exports&&"object"==typeof module?module.exports=n():"function"==typeof define&&define.amd?define([],n):"object"==typeof exports?exports.SendBird=n():e.SendBird=n()}("undefined"!=typeof self?self:this,function(){function e(){this.oldIE=!0,this.boundary="--------FormData"+Math.random(),this._fields=[]}var n,t=!1,r="wss://ws.sendbird.com",i="https://api.sendbird.com",a=1e3,s=9e3;try{n=window.console||{log:function(){}}}catch(e){n={log:function(){}}}var o="undefined";try{o=navigator.userAgent.replace(/,/g,".")}catch(e){o="undefined"}var l,u="JS,"+o+",3.0.75,",c=function(){try{if(document&&9===document.documentMode)return!0}catch(e){return!1}return!1}(),d=function(){try{if(document&&document.documentMode<=8)return!0}catch(e){return!1}return!1}();if(c||d)"function"!=typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")}),"function"!=typeof Array.prototype.forEach&&(Arr

ReferenceError: navigator is not defined
    at new c (/node_modules/sendbird/SendBird.min.js:5:3026)
    at new v (/node_modules/sendbird/SendBird.min.js:5:4022)
    at new e (/node_modules/sendbird/SendBird.min.js:10:13498)

**Comment by paulferrett** [comment]
Hi @Alchemist85K - I see you guys just pushed a `3.0.76` update. That fixes the navigator issue.

Now I get the following :(

```
/node_modules/sendbird/SendBird.min.js:7
this.isAckRequired=function(){return"MESG"===this.command||"FILE"===this.command||"ENTR"===this.command||"EXIT"===this.command||"READ"===this.command||"MEDI"===this.command||"FEDI"===this.command},this.encode=function(){return this.command+this.payload+"\n"},this.decode=function(e){e=e.trim(),this.command=e.substring(0,4),this.payload=e.substring(4)},this.getJsonElement=function(){return JSON.parse(this.payload)},this.isRequestIdCommand=function(){return this.isAckRequired()||"EROR"===this.command},this.command,this.payload,this.requestId;var r=this;if(0!==arguments.length){var i;switch(arguments.length){case 1:var a=arguments[0];if(!a||a.length<=4)return r.command="NOOP",void(r.payload="{}");if(a=a.trim(),r.command=a.substring(0,4),r.payload=a.substring(4),r.isRequestIdCommand()){var s=r.getJsonElement();s&&(r.requestId=s.hasOwnProperty("req_id")?s.req_id:"")}break;case 3:i=arguments[2];case 2:var o=arguments[0],l=arguments[1];i=i||"",r.co

TypeError: e.stop is not a function
    at Timeout._onTimeout (/node_modules/sendbird/SendBird.min.js:7:19991)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

To Reproduce:
* Start node process
* Turn off wifi
* wait a few seconds...

**Comment by Alchemist85K** [comment]
@paulferrett 
I'm so sorry.
JavaScript SDK version 3.0.77 has released. 
Please use the latest version. 
Thank you.

**Comment by paulferrett** [comment]
Great, thanks very much :)
