### ISSUE TITLE
sendFileMessage in NodeJs

### ISSUE THREAD

**Issue by mabilbao** [smilefam/SendBird-JavaScript#85]
Hey guys,

I am doing an implementation in NodeJs and I need to put files in a conversation as a message. I read the documentation and I see I could not send a file by the API, so I am trying to send the file by  SDK.

This is my example:
```javascript
    async sendFile(conversationId, userId) {
        try {
            const messengerSdk = new MessengerSdk({appId: MessengerConf.appId})
            const user = await this.getUser(userId)
            
            const sendFilePromise = new Promise((resolve, reject) => {
                messengerSdk.connect(userId, user.access_token, (user, error) => {
                    if (error) return reject(error)
                    
                    messengerSdk.GroupChannel.getChannel(conversationId, (channel, error) => {
                        if (error) return reject(error)

                        // const thumbSizeList = [{"maxWidth": "160", "maxHeight": "160"}]
                        const file = fs.readFileSync('./test/example.gif')
                        
                        channel.sendFileMessage(
                            file,
                            (fileMessage, error) => {
                                if (error) {
                                    console.log('Error ====> ')
                                    return reject(error)
                                }
                                
                                console.log('OK =====> ')
                                return resolve(fileMessage)
                            }) 
                    })
                })
            })
            return await sendFilePromise
        } catch(exception) {
            this.loggerError(exception)
            return exception
        }
    }
```

I am getting the following error:
```
ReferenceError: FormData is not defined
    at U.upload (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:11143)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21709
    at _e.checkRouting (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21400)
    at n (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21557)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:9:7557
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7731
    at Array.forEach (<anonymous>)
    at Ce.processAllReadyHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7686)
    at Ce.ready (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7501)
    at _e.uploadFile (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:9:7510)
    at I (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:23818)
    at n.l.onChangeHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22043)
    at n.value (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:555)
    at h (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22698)
    at n.c.onChangeHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22522)
    at n.value (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:555)
    at k.addTask (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:24895)
    at x.V.sendFileMessage (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:6:4585)
    at messengerSdk.GroupChannel.getChannel (/Users/martinbilbao/Code/marketplace-webhooks/src/services/messengerService.js:104:33)
    at O (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:11744)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:7:16641
    at f (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:3883)
```

I understand this is happening because from NodeJs I don't have `Blob` class to be used into this method, but I can't understand why I can use `Buffer`to replace it.

Could anybody help me with that?

Node version: 10.7.0
Sendbird SDK version: 3.0.97

**Comment by supertopoz** [comment]
@mabilbao We will take a look at your code and get back a soon as possible.

**Comment by supertopoz** [comment]
@mabilbao I checked out your case. 

The SendBird SDK is built for client side operations so will not work as expected in a node.js. It would be cool if you can find a way, but I'm sorry we currently can't pursue this further. 

I'm not sure if this helps but to let you know file argument accepts a Blob, a file or a string. 

Again, the intend use of the JS SDK is for client side operations, but you are welcome to have a try.

**Comment by mabilbao** [comment]
@supertopoz I got it, but understanding we could not use Sendbird API to upload files and we can not use Sendbird SDK from the server side to upload files, what do you recommend me?

We are working in a project which must send messages and files from NodeJS and we need a solution for that.

I tried a new example sending a Blob file installing JSDOM in the project:
```javascript
async sendFile(conversationId, userId, file, name, contentType, size) {
  try {
    const messengerSdk = new MessengerSdk({appId: MessengerConf.appId})
    const user = await this.getUser(userId)

    const sendFilePromise = new Promise((resolve, reject) => {
      messengerSdk.connect(userId, user.access_token, (user, error) => {
        if (error) return reject(error)

        messengerSdk.GroupChannel.getChannel(conversationId, (channel, error) => {
          if (error) return reject(error)

          const thumbSizeList = [{maxWidth: "160", maxHeight: "160"}]

          const { JSDOM } = require('jsdom')
          const dom = new JSDOM(`
            <!DOCTYPE html>
            <body>
              <input type="file">
            </body>
          `)
          const { window } = dom

          // let file = fs.readFileSync('./test/example.gif')
          let base64File = file.toString('base64')
          var byteCharacters = window.atob(base64File);
          var byteNumbers = new Array(byteCharacters.length);
          for (var i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
          }
          var byteArray = new Uint8Array(byteNumbers);
          let blobFile = new window.Blob([byteArray], {type: contentType})

          channel.sendFileMessage(
            blobFile,
            (fileMessage, error) => {
                if (error) {
                    console.log('Error ====> ', error)
                    return reject(error)
                }

                console.log('OK')
                console.log(fileMessage)
                return resolve(fileMessage)
          })
        })
      })
    })
    return await sendFilePromise
  } catch(exception) {
    this.loggerError(exception)
    return exception
  }
} 
```

I am getting the following error:

```
ReferenceError: FormData is not defined
    at U.upload (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:11143)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21709
    at _e.checkRouting (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21400)
    at n (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:8:21557)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:9:7557
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7731
    at Array.forEach (<anonymous>)
    at Ce.processAllReadyHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7686)
    at Ce.ready (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:10:7501)
    at _e.uploadFile (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:9:7510)
    at I (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:23818)
    at n.l.onChangeHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22043)
    at n.value (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:555)
    at h (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22698)
    at n.c.onChangeHandler (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:22522)
    at n.value (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:555)
    at k.addTask (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:24895)
    at x.V.sendFileMessage (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:6:4585)
    at messengerSdk.GroupChannel.getChannel (/Users/martinbilbao/Code/marketplace-webhooks/src/services/messengerService.js:140:21)
    at O (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:11744)
    at /Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:7:16641
    at f (/Users/martinbilbao/Code/marketplace-webhooks/node_modules/sendbird/SendBird.min.js:5:3883)
```

Any option?

**Comment by supertopoz** [comment]
@mabilbao I'd like to recommend uploading the files to your own storage facility, then appending messages to the chat with the file details including the url of the file using the Platform API.

**Comment by mabilbao** [comment]
@supertopoz we use Sendbird Javascript SDK to upload files from the client side as well - we have a Messenger in our application. In this application, we upload files using `sendFileMessage` function and we use `thumbSizeList`. Just to close this GitHub issue, the only solution to this problem is:
* We should upload files to our own AWS S3 instance from server-side although we are already uploading files to your AWS S3 instance from our Messenger using `thumbSizeList`. Is this correct?

**Question:**
* Could we use `thumbSizeList` if we would send only the `FILE_URL`?
